### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LeonusDH** [ichorpowered/protocolcontrol#1]
Sponge - 7.3.0

https://pastebin.com/QRQ0YQVC

**Comment by vectrixdevelops** [comment]
@LeonusDH Apologies it took me a while to get to this. Did you put ProtocolControl into the mods folder? You cannot put this in any subfolder/plugins folder as this doesn't seem to load the access transformers correctly.

**Comment by LeonusDH** [comment]
I put it in a subfolder.

**Comment by vectrixdevelops** [comment]
Yeah make sure to always put this in the mods folder. I will update the README to detail this soon.
